#!/usr/bin/env python
import sys

def usage():
  print """usage: %s [options]
  --refresh            : refresh the subscribed feeds
  --import <opml_file> : import subscriptions from a OPML file
  --server             : run the built-in web server
  -v                   : be more verbose (can be repeated)
  """ % sys.argv[0]
  sys.exit(0)

if __name__ == '__main__':
  import getopt
  opts, args = getopt.getopt(sys.argv[1:], 'v',
                             ['refresh', 'server', 'import='])
  if opts == []:
    usage()
  for opt, val in opts:
    if opt == '--refresh':
      import update
      update.update()
    elif opt == '--import':
      import opml
      opml.import_opml(val)
    elif opt == '--server':
      import update, server
      updater = update.PeriodicUpdater()
      updater.start()
      server.run()
