#!/usr/bin/env python
import sys, os

# XXX TODO
# XXX pacing

def usage():
  print """usage: %s [options]
  --refresh            : refresh the subscribed feeds
  --import <opml_file> : import subscriptions from a OPML file
  --server             : run the built-in web server
  --kill               : kill the server
  --cleanup            : perform database housekeeping and cleanup
  -v                   : be more verbose (can be repeated)
  -h, --help           : print this help text
  """ % sys.argv[0]
  sys.exit(0)

if __name__ == '__main__':
  import getopt
  try:
    import param
  except ImportError:
    print >> sys.stderr, 'You must create a param.py file, possibly using',
    print >> sys.stderr, 'param.py.sample as an example'
    sys.exit(0)
  try:
    import transform
  except ImportError:
    print >> sys.stderr, 'You must create a transform.py file, possibly using',
    print >> sys.stderr, 'transform.py.sample as an example'
    sys.exit(0)
  import util
  opts, args = getopt.getopt(
    sys.argv[1:], 'vh',
    ['refresh', 'resync', 'server', 'import=', 'kill', 'help',
     'clean', 'cleanup'])
  if opts == []:
    # try to detect if we are being called as a CGI script
    cgi_ver = os.getenv('GATEWAY_INTERFACE')
    if cgi_ver and cgi_ver.startswith('CGI/'):
      import server
      server.do_cgi()
    else:
      usage()
  for opt, val in opts:
    if opt in ['-h', '--help']:
      usage()
    if opt == '--refresh':
      import update
      try:
        update.update()
      except:
        util.print_stack()
        sys.exit(1)
    if opt == '--resync':
      import update
      try:
        update.update('and feed_errors > 0')
      except:
        util.print_stack()
        sys.exit(1)
    elif opt == '--import':
      import opml
      opml.import_opml(val)
    elif opt == '--server':
      import update, server
      # close stdin file descriptor
      try:
        import posix
        posix.close(0)
        posix.open('/dev/null', posix.O_RDONLY)
      except ImportError:
        pass
      updater = update.PeriodicUpdater()
      updater.start()
      rater = update.RatingsWorker(update.ratings_q)
      rater.start()
      server.run()
    elif opt == '--kill':
      import os
      pid = int(open('temboz.pid').readline().strip())
      os.kill(pid, 9)
      os.remove('temboz.pid')
    elif opt in ['--clean', '--cleanup']:
      import update
      try:
        update.cleanup()
      except:
        util.print_stack()
        sys.exit(1)
# http://bayazid.kefta.com/~majid/temboz/nph-temboz.cgi/view?feed_uid=1
